#!/usr/bin/env python3
"""Generates internal/unicode/tables.mbt from Python's unicodedata.

Rust's `unicode-ident` (XID_Start / XID_Continue), `char::is_uppercase`,
`char::is_lowercase`, case folding (`unicase`) and the full case mappings used by `str::to_uppercase` /
`str::to_lowercase` are approximated with the Unicode database shipped with
the running Python interpreter.
"""
import sys
import unicodedata

MAX = 0x110000


def ranges(pred):
    out = []
    start = None
    for cp in range(MAX):
        if 0xD800 <= cp <= 0xDFFF:
            ok = False
        else:
            ok = pred(cp)
        if ok and start is None:
            start = cp
        elif not ok and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, MAX - 1))
    return out


def xid_start(cp):
    c = chr(cp)
    return c.isidentifier() and c != "_"


def xid_continue(cp):
    c = chr(cp)
    return ("a" + c).isidentifier()


def uppercase(cp):
    # CPython derives `isupper` for a single character from the Uppercase
    # property, which is what Rust's `char::is_uppercase` uses.
    return chr(cp).isupper()


def lowercase(cp):
    return chr(cp).islower()


def cased(cp):
    c = chr(cp)
    return c.isupper() or c.islower() or unicodedata.category(c) == "Lt"


# Word_Break=MidLetter/MidNumLet/Single_Quote characters (part of Case_Ignorable)
WORD_BREAK_MID = set(
    "\u0027\u002e\u003a\u00b7\u0387\u055f\u05f4\u2018\u2019\u2024\u2027"
    "\ufe13\ufe52\ufe55\uff07\uff0e\uff1a"
)


def case_ignorable(cp):
    c = chr(cp)
    return unicodedata.category(c) in ("Mn", "Me", "Cf", "Lm", "Sk") or c in WORD_BREAK_MID


def emit_ranges(out, name, rs):
    out.append("///|")
    out.append(f"let {name} : FixedArray[Int] = [")
    for a, b in rs:
        out.append(f"  0x{a:x}, 0x{b:x},")
    out.append("]")
    out.append("")


def emit_mapping(out, name, fn):
    single = []
    multi = []
    for cp in range(MAX):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        c = chr(cp)
        m = fn(c)
        if m == c:
            continue
        if len(m) == 1:
            single.append((cp, ord(m)))
        else:
            multi.append((cp, m))
    out.append("///|")
    out.append(f"let {name}_single : FixedArray[Int] = [")
    for a, b in single:
        out.append(f"  0x{a:x}, 0x{b:x},")
    out.append("]")
    out.append("")
    out.append("///|")
    out.append(f"let {name}_multi_keys : FixedArray[Int] = [")
    for a, _ in multi:
        out.append(f"  0x{a:x},")
    out.append("]")
    out.append("")
    out.append("///|")
    out.append(f"let {name}_multi_values : FixedArray[String] = [")
    for _, m in multi:
        esc = "".join(f"\\u{{{ord(ch):x}}}" for ch in m)
        out.append(f'  "{esc}",')
    out.append("]")
    out.append("")


def main():
    out = [
        "// Code generated by scripts/gen_unicode_tables.py; DO NOT EDIT.",
        f"// Unicode version: {unicodedata.unidata_version}",
        "",
    ]
    emit_ranges(out, "xid_start_table", ranges(xid_start))
    emit_ranges(out, "xid_continue_table", ranges(xid_continue))
    emit_ranges(out, "uppercase_table", ranges(uppercase))
    emit_ranges(out, "lowercase_table", ranges(lowercase))
    emit_ranges(out, "cased_table", ranges(cased))
    emit_ranges(out, "case_ignorable_table", ranges(case_ignorable))
    emit_mapping(out, "upper", lambda c: c.upper())
    # Python lowercases U+0130 to "i̇" like Rust; final sigma is handled
    # by the caller.
    emit_mapping(out, "lower", lambda c: c.lower())
    emit_mapping(out, "fold", lambda c: c.casefold())
    path = sys.argv[1] if len(sys.argv) > 1 else "internal/unicode/tables.mbt"
    with open(path, "w") as f:
        f.write("\n".join(out))


if __name__ == "__main__":
    main()
